import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from './components/Header';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
        <Header />
        <main className="container mx-auto p-4">{children}</main>
        </body>
        </html>
    );
}
